# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elppd <- function(Y, theta, sigma, eta) {
    .Call(`_anchoredmixtures_elppd`, Y, theta, sigma, eta)
}

elppd_M <- function(Y, theta, sigma, eta) {
    .Call(`_anchoredmixtures_elppd_M`, Y, theta, sigma, eta)
}

update_sticks <- function(Svec, avec, bvec) {
    .Call(`_anchoredmixtures_update_sticks`, Svec, avec, bvec)
}

calculate_weights <- function(sticks) {
    .Call(`_anchoredmixtures_calculate_weights`, sticks)
}

update_allocations <- function(y, theta, sigma, eta) {
    .Call(`_anchoredmixtures_update_allocations`, y, theta, sigma, eta)
}

enforce_anchors <- function(A, s) {
    .Call(`_anchoredmixtures_enforce_anchors`, A, s)
}

log_post_e0 <- function(e0, K, Nvec, e0_ha0, e0_hb0) {
    .Call(`_anchoredmixtures_log_post_e0`, e0, K, Nvec, e0_ha0, e0_hb0)
}

e0_accept_prob <- function(proposed_e0, e0, K, Nvec, e0_ha0, e0_hb0) {
    .Call(`_anchoredmixtures_e0_accept_prob`, proposed_e0, e0, K, Nvec, e0_ha0, e0_hb0)
}

update_e0 <- function(current_e0, K, Svec, e0_ha0, e0_hb0, prop_std = 5e-2) {
    .Call(`_anchoredmixtures_update_e0`, current_e0, K, Svec, e0_ha0, e0_hb0, prop_std)
}

Kplus <- function(K, Svec) {
    .Call(`_anchoredmixtures_Kplus`, K, Svec)
}

update_b0_indprior_SFM <- function(gamma, k, a0, ghyp, hhyp) {
    .Call(`_anchoredmixtures_update_b0_indprior_SFM`, gamma, k, a0, ghyp, hhyp)
}

update_lambda_NG_SFM <- function(gamma, k, mu0, R0, nu1, nu2) {
    .Call(`_anchoredmixtures_update_lambda_NG_SFM`, gamma, k, mu0, R0, nu1, nu2)
}

update_mu0_NG_SFM <- function(gamma, k, R0, lambda, m0, M0) {
    .Call(`_anchoredmixtures_update_mu0_NG_SFM`, gamma, k, R0, lambda, m0, M0)
}

melt_probmatrix <- function(probM) {
    .Call(`_anchoredmixtures_melt_probmatrix`, probM)
}

sort_probmatrix <- function(melt_probM, sort_col) {
    .Call(`_anchoredmixtures_sort_probmatrix`, melt_probM, sort_col)
}

check_if_done <- function(current_counts, max_counts) {
    .Call(`_anchoredmixtures_check_if_done`, current_counts, max_counts)
}

in_matrix <- function(value, M) {
    .Call(`_anchoredmixtures_in_matrix`, value, M)
}

find_anchored <- function(P_sorted, m_vec, k) {
    .Call(`_anchoredmixtures_find_anchored`, P_sorted, m_vec, k)
}

std_normal_pdf <- function(y) {
    .Call(`_anchoredmixtures_std_normal_pdf`, y)
}

normal_pdf <- function(y, theta, sigma) {
    .Call(`_anchoredmixtures_normal_pdf`, y, theta, sigma)
}

log_normal_pdf <- function(y, theta, sigma) {
    .Call(`_anchoredmixtures_log_normal_pdf`, y, theta, sigma)
}

gamma_pdf <- function(y, a, b) {
    .Call(`_anchoredmixtures_gamma_pdf`, y, a, b)
}

log_gamma_pdf <- function(y, a, b) {
    .Call(`_anchoredmixtures_log_gamma_pdf`, y, a, b)
}

normal_pdf_arma <- function(y, theta, sigma, sum = TRUE, log = TRUE) {
    .Call(`_anchoredmixtures_normal_pdf_arma`, y, theta, sigma, sum, log)
}

gamma_pdf_arma <- function(y, a, b, sum = TRUE, log = TRUE) {
    .Call(`_anchoredmixtures_gamma_pdf_arma`, y, a, b, sum, log)
}

rnormArma <- function(n, mu, sigma) {
    .Call(`_anchoredmixtures_rnormArma`, n, mu, sigma)
}

allocationprobs_univ_normal <- function(y, theta, sigma, eta) {
    .Call(`_anchoredmixtures_allocationprobs_univ_normal`, y, theta, sigma, eta)
}

mixture_likelihoods_univ_normal <- function(y, theta, sigma, eta, sum = TRUE, logt = TRUE) {
    .Call(`_anchoredmixtures_mixture_likelihoods_univ_normal`, y, theta, sigma, eta, sum, logt)
}

logsumexp_vec <- function(avec) {
    .Call(`_anchoredmixtures_logsumexp_vec`, avec)
}

logsumexp <- function(a, b) {
    .Call(`_anchoredmixtures_logsumexp`, a, b)
}

normalize_A <- function(A) {
    .Call(`_anchoredmixtures_normalize_A`, A)
}

normalize_A_reg <- function(A) {
    .Call(`_anchoredmixtures_normalize_A_reg`, A)
}

normalize_vec <- function(v) {
    .Call(`_anchoredmixtures_normalize_vec`, v)
}

normalize_logvec <- function(lv) {
    .Call(`_anchoredmixtures_normalize_logvec`, lv)
}

nvec_count <- function(svec, k) {
    .Call(`_anchoredmixtures_nvec_count`, svec, k)
}

ordered_remove <- function(list, index) {
    .Call(`_anchoredmixtures_ordered_remove`, list, index)
}

ordered_insert_next <- function(list) {
    .Call(`_anchoredmixtures_ordered_insert_next`, list)
}

ordered_next <- function(list) {
    .Call(`_anchoredmixtures_ordered_next`, list)
}

in_vec_int <- function(n, v) {
    .Call(`_anchoredmixtures_in_vec_int`, n, v)
}

which_vec_int <- function(n, v) {
    .Call(`_anchoredmixtures_which_vec_int`, n, v)
}

int_seq <- function(k) {
    .Call(`_anchoredmixtures_int_seq`, k)
}

rcpparma_hello_world <- function() {
    .Call(`_anchoredmixtures_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_anchoredmixtures_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_anchoredmixtures_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_anchoredmixtures_rcpparma_bothproducts`, x)
}

update_theta_indprior <- function(cvector, Y, precision, kappa, mu0) {
    .Call(`_anchoredmixtures_update_theta_indprior`, cvector, Y, precision, kappa, mu0)
}

update_precision_indprior <- function(cvector, Y, theta, a0, b0) {
    .Call(`_anchoredmixtures_update_precision_indprior`, cvector, Y, theta, a0, b0)
}

update_b0_gammaprior <- function(a0, g0, h0, precision) {
    .Call(`_anchoredmixtures_update_b0_gammaprior`, a0, g0, h0, precision)
}

lb_ind_MAP_b <- function(Y, theta, sigma, eta, kappa, mu0, a0, b0, g0, h0) {
    .Call(`_anchoredmixtures_lb_ind_MAP_b`, Y, theta, sigma, eta, kappa, mu0, a0, b0, g0, h0)
}

lb_ind_MAP_b_A <- function(Y, theta, sigma, eta, kappa, mu0, a0, b0, g0, h0, Cm, Am) {
    .Call(`_anchoredmixtures_lb_ind_MAP_b_A`, Y, theta, sigma, eta, kappa, mu0, a0, b0, g0, h0, Cm, Am)
}

lb_ind_MAP <- function(Y, theta, sigma, eta, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_lb_ind_MAP`, Y, theta, sigma, eta, kappa, mu0, a0, b0)
}

lb_ind_MAP_A <- function(Y, theta, sigma, eta, kappa, mu0, a0, b0, Cm, Am) {
    .Call(`_anchoredmixtures_lb_ind_MAP_A`, Y, theta, sigma, eta, kappa, mu0, a0, b0, Cm, Am)
}

log_priordensity_gamma_indprior <- function(gamma, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_log_priordensity_gamma_indprior`, gamma, kappa, mu0, a0, b0)
}

sample_gamma_indprior <- function(kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_indprior`, kappa, mu0, a0, b0)
}

sample_gamma_indprior_mat <- function(nsamples, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_indprior_mat`, nsamples, kappa, mu0, a0, b0)
}

update_gammaj_indprior_SFM <- function(component, y, s, gamma, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_update_gammaj_indprior_SFM`, component, y, s, gamma, kappa, mu0, a0, b0)
}

update_gamma_indprior_SFM <- function(K, y, s, gamma, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_update_gamma_indprior_SFM`, K, y, s, gamma, kappa, mu0, a0, b0)
}

exp_inf <- function(x) {
    .Call(`_anchoredmixtures_exp_inf`, x)
}

sample_gamma_conjprior <- function(kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_conjprior`, kappa, mu0, a0, b0)
}

sample_gamma_conjprior_mat <- function(nsamples, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_conjprior_mat`, nsamples, kappa, mu0, a0, b0)
}

update_gammaj_conjprior_SFM <- function(component, y, s, gamma, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_update_gammaj_conjprior_SFM`, component, y, s, gamma, kappa, mu0, a0, b0)
}

update_gamma_conjprior_SFM <- function(K, y, s, gamma, kappa, mu0, a0, b0) {
    .Call(`_anchoredmixtures_update_gamma_conjprior_SFM`, K, y, s, gamma, kappa, mu0, a0, b0)
}

sample_gamma_unifprior <- function(Rlow, Rup, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_unifprior`, Rlow, Rup, a0, b0)
}

sample_gamma_unifprior_mat <- function(nsamples, Rlow, Rup, a0, b0) {
    .Call(`_anchoredmixtures_sample_gamma_unifprior_mat`, nsamples, Rlow, Rup, a0, b0)
}

update_gammaj_unifprior_SFM <- function(component, y, s, gamma, Rlow, Rup, a0, b0) {
    .Call(`_anchoredmixtures_update_gammaj_unifprior_SFM`, component, y, s, gamma, Rlow, Rup, a0, b0)
}

update_gamma_unifprior_SFM <- function(K, y, s, gamma, Rlow, Rup, a0, b0) {
    .Call(`_anchoredmixtures_update_gamma_unifprior_SFM`, K, y, s, gamma, Rlow, Rup, a0, b0)
}

